### ISSUE TITLE
Error java.util.NoSuchElementException importing Swagger to SoapUI

### ISSUE THREAD

**Issue by bayani88** [olensmar/soapui-swagger-plugin#20]
I'm having issues importing Swagger to SoapUI 5.2.0.  I am able to partially import the swagger definition, but then this error occurs. Any thoughts on why this error is occurring or how I can import ? 

I've tried both the open source and trial version of soapui ng.  I am able to import in very small chunks (1 at a time).  However as a group the import is interrupted due to this error.  

These definitions imported without issues
/api/product/{id}
/api/product/View

These did not originally import, but could be imported individually.  
/api/product/{id}/Something
/api/product/{id}/Something/{Type}
/api/product/{id}/Something/{Type}/View

Below is a copy of the Error log in SoapUI.

Mon Jul 27 10:49:42 CDT 2015:ERROR:java.util.NoSuchElementException
   java.util.NoSuchElementException
   	at java.util.Collections$EmptyIterator.next(Unknown Source)
   	at java_util_Iterator$next$0.call(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)
   	at com.smartbear.swagger.Swagger2Importer$_addOperation_closure3.doCall(Swagger2Importer.groovy:174)
   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   	at java.lang.reflect.Method.invoke(Unknown Source)
   	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
   	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
   	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
   	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
   	at groovy.lang.Closure.call(Closure.java:423)
   	at groovy.lang.Closure.call(Closure.java:439)
   	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5225)
   	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2104)
   	at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
   	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:84)
   	at com.smartbear.swagger.Swagger2Importer.addOperation(Swagger2Importer.groovy:164)
   	at com.smartbear.swagger.Swagger2Importer$addOperation.callCurrent(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:179)
   	at com.smartbear.swagger.Swagger2Importer.importPath(Swagger2Importer.groovy:114)
   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   	at java.lang.reflect.Method.invoke(Unknown Source)
   	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
   	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
   	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:382)
   	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
   	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:179)
   	at com.smartbear.swagger.Swagger2Importer$_importSwagger_closure1.doCall(Swagger2Importer.groovy:68)
   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   	at java.lang.reflect.Method.invoke(Unknown Source)
   	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
   	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
   	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
   	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
   	at groovy.lang.Closure.call(Closure.java:423)
   	at groovy.lang.Closure.call(Closure.java:439)
   	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5225)
   	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2104)
   	at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
   	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
   	at com.smartbear.swagger.Swagger2Importer.importSwagger(Swagger2Importer.groovy:67)
   	at com.smartbear.swagger.SwaggerImporter$importSwagger.call(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
   	at com.smartbear.swagger.SwaggerUtils$1.construct(SwaggerUtils.groovy:64)
   	at com.eviware.soapui.support.swing.SwingWorkerDelegator.construct(SwingWorkerDelegator.java:48)
   	at com.eviware.soapui.support.swing.SwingWorker.run(SwingWorker.java:88)

**Comment by plog17** [comment]
Same bug here. I'd be happy to have any input in order to track that bug.

**Comment by olensmar** [comment]
hm... are you getting this with 5.2.1 also?

**Comment by plog17** [comment]
Updated to 5.2.1
Problem solved.

Thanks @olensmar !

**Comment by plog17** [comment]
I admit that I am curious a bit...
Was I lucky on the timing or did you simply release a fix after reading my comment ?

![image](https://cloud.githubusercontent.com/assets/4535664/10320207/59b97f48-6c40-11e5-9b60-5dfe60d6cfa9.png)

In both cases, I like that Import Swagger feature. It really saves us time!
Thanks!

**Comment by olensmar** [comment]
wow - awesome!
